export const genres = [
    "acid-jazz", "afrobeat", "alt-rock", "alternative", "ambient", 
    "avant-garde", "black-metal", "bluegrass", "blues", "bossanova", 
    "breakbeat", "cantopop", "chillwave", "classical", "country", 
    "dance", "dark-ambient", "death-metal", "deep-house", "disco", 
    "doom-metal", "drone", "drum-and-bass", "dub", "dubstep", "dream-pop", 
    "edm", "electro", "electroclash", "electronic", "emo", "folk", 
    "folk-metal", "funk", "garage", "glitch", "gospel", "goth", 
    "grindcore", "grunge", "hard-bop", "hard-rock", "hard-trance", 
    "hardcore", "heavy-metal", "hip-hop", "house",
    "idm", "indie", "indie-pop", "industrial", "j-pop", "jazz", 
    "jungle", "k-pop", "krautrock", "kwaito", "latin", "mandopop", "math-rock", 
    "metal", "metalcore", "metropopolis", "neoclassical", "new-age", 
    "new-wave", "norwegian-black-metal", "nu-metal", "opera", "pop", "post-dubstep", 
    "post-rock", "power-pop", "progressive-house", "psych-rock", "punk", 
    "punk-rock", "r-n-b", "reggae", "riot-grrrl", "rock", 
    "rockabilly", "shoegaze", "singer-songwriter", "ska", "ska-punk", 
    "sludge-metal", "soul", "synth-pop", "synthwave", "techno", "trance", 
    "trip-hop", "vaporwave", "world-music"
];