export const genres = [
    "acid-jazz", "afrobeat", "alt-rock", "alternative", "ambient", 
    "avant-garde", "black-metal", "bluegrass", "blues", "bossanova", 
    "breakbeat", "cantopop", "chillwave", "classical", "country", 
    "dance", "dark-ambient", "death-metal", "deep-house", "disco", 
    "doom-metal", "drone", "drum-and-bass", "dub", "dubstep", "dream-pop", 
    "edm", "electro", "electroclash", "electronic", "emo", "folk", 
    "folk-metal", "forro", "funk", "garage", "glitch", "gospel", "goth", 
    "grindcore", "grunge", "hard-bop", "hard-rock", "hard-trance", 
    "hardcore", "hardstyle", "heavy-metal", "hip-hop", "honky-tonk", 
    "house", "idm", "indie", "indie-pop", "industrial", "j-pop", "jazz", 
    "jungle", "k-pop", "krautrock", "latin", "mandopop", "math-rock", 
    "metal", "metalcore", "minimal-techno", "neoclassical", "new-age", 
    "new-wave", "nu-metal", "opera", "pagode", "pop", "post-dubstep", 
    "post-rock", "power-pop", "progressive-house", "psych-rock", "punk", 
    "punk-rock", "r-n-b", "reggae", "reggaeton", "rock", "rock-n-roll", 
    "rockabilly", "shoegaze", "show-tunes", "singer-songwriter", "ska", 
    "sludge-metal", "soul", "synth-pop", "synthwave", "techno", "trance", 
    "trip-hop", "vaporwave", "world-music"
];